<?php
// File: blog.php
require_once 'includes/db.php';
require_once 'includes/helpers.php';

// Pagination
$page = isset($_GET['page']) ? (int)$_GET['page'] : 1;
$limit = 9; 
$offset = ($page - 1) * $limit;

// Database Fetch
try {
    $stmt = $db->prepare("SELECT * FROM blogs WHERE status='published' ORDER BY created_at DESC LIMIT ? OFFSET ?");
    $stmt->bindValue(1, $limit, PDO::PARAM_INT);
    $stmt->bindValue(2, $offset, PDO::PARAM_INT);
    $stmt->execute();
    $blogs = $stmt->fetchAll();

    $total_blogs = $db->query("SELECT COUNT(*) FROM blogs WHERE status='published'")->fetchColumn();
    $total_pages = ceil($total_blogs / $limit);
} catch (Exception $e) {
    $blogs = [];
    $total_pages = 0;
}

// SEO
$page_title = "Blog - Secrets of Social Media Growth";
ob_start();
include 'user/_header.php';
$header_html = ob_get_clean();
// Force Title Update using Regex
$header_html = preg_replace('/<title>(.*?)<\/title>/', "<title>$page_title</title>", $header_html);
echo $header_html;
?>

<div class="relative bg-[#0f172a] pt-32 pb-20 overflow-hidden">
    <div class="absolute top-0 left-0 w-full h-full overflow-hidden z-0">
        <div class="absolute top-[-10%] left-[-10%] w-[40%] h-[40%] rounded-full bg-indigo-600/20 blur-[100px] animate-pulse"></div>
        <div class="absolute bottom-[-10%] right-[-10%] w-[40%] h-[40%] rounded-full bg-purple-600/20 blur-[100px] animate-pulse" style="animation-delay: 2s"></div>
    </div>

    <div class="max-w-7xl mx-auto px-6 relative z-10 text-center">
        <span class="inline-block py-1 px-3 rounded-full bg-indigo-500/10 border border-indigo-500/30 text-indigo-400 text-sm font-bold tracking-wider mb-6 animate-fade-in-up">
            ✨ AI POWERED INSIGHTS
        </span>
        <h1 class="text-5xl md:text-7xl font-extrabold text-white tracking-tight mb-6 leading-tight animate-fade-in-up" style="animation-delay: 0.1s">
            Master the <span class="text-transparent bg-clip-text bg-gradient-to-r from-indigo-400 via-purple-400 to-pink-400">Algorithm.</span>
        </h1>
        <p class="text-lg text-slate-400 max-w-2xl mx-auto mb-10 animate-fade-in-up" style="animation-delay: 0.2s">
            Discover the latest strategies to grow your TikTok, Instagram, and YouTube. Automated content generated by our intelligent AI engine.
        </p>
    </div>
</div>

<div class="bg-slate-50 min-h-screen py-20 relative">
    <div class="max-w-7xl mx-auto px-6">
        
        <?php if(!empty($blogs)): ?>
            <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-10">
                <?php foreach($blogs as $index => $blog): 
                    // Random Gradients for Cards
                    $gradients = [
                        'from-blue-600 to-indigo-700',
                        'from-purple-600 to-pink-600',
                        'from-emerald-500 to-teal-700',
                        'from-orange-500 to-red-600'
                    ];
                    $bg_class = $gradients[$index % count($gradients)];
                    $delay = ($index % 3) * 100; // Staggered animation
                ?>
                
                <article class="group relative bg-white rounded-[2rem] shadow-xl hover:shadow-2xl transition-all duration-500 border border-slate-100 overflow-hidden flex flex-col h-full hover:-translate-y-2" data-aos="fade-up" data-aos-delay="<?= $delay ?>">
                    
                    <div class="h-56 w-full bg-gradient-to-br <?= $bg_class ?> relative overflow-hidden flex items-center justify-center p-6 group-hover:scale-105 transition-transform duration-700">
                        <div class="absolute inset-0 bg-[url('assets/img/grid.svg')] opacity-20"></div>
                        <h2 class="text-2xl font-bold text-white text-center leading-snug drop-shadow-md line-clamp-3">
                            <?= htmlspecialchars($blog['title']) ?>
                        </h2>
                    </div>

                    <div class="p-8 flex-1 flex flex-col relative">
                        <div class="absolute -top-5 right-8 bg-slate-900 text-white text-xs font-bold py-2 px-4 rounded-full shadow-lg border border-slate-700">
                            <?= date('M d', strtotime($blog['created_at'])) ?>
                        </div>

                        <div class="flex items-center gap-3 mb-4 text-xs font-bold text-slate-400 uppercase tracking-widest">
                            <span class="flex items-center gap-1"><i data-lucide="eye" class="w-3 h-3"></i> <?= number_format($blog['views']) ?> Views</span>
                            <span>•</span>
                            <span>5 Min Read</span>
                        </div>

                        <p class="text-slate-500 text-sm leading-relaxed mb-6 line-clamp-3 flex-1">
                            <?= htmlspecialchars(substr($blog['meta_desc'], 0, 120)) ?>...
                        </p>

                        <div class="mt-auto border-t border-slate-100 pt-6 flex justify-between items-center">
                            <span class="text-slate-400 text-sm font-medium">By LikexFollow AI</span>
                            
                            <a href="blog_view.php?slug=<?= $blog['slug'] ?>" class="relative inline-flex items-center justify-center px-6 py-2.5 overflow-hidden font-bold text-white transition-all duration-300 bg-indigo-600 rounded-full group-hover:bg-indigo-700 group-hover:scale-105 focus:outline-none focus:ring-2 focus:ring-indigo-400 focus:ring-offset-2">
                                <span class="relative flex items-center gap-2">
                                    Read Article <i data-lucide="arrow-right" class="w-4 h-4"></i>
                                </span>
                            </a>
                        </div>
                    </div>
                </article>
                <?php endforeach; ?>
            </div>

            <?php if($total_pages > 1): ?>
            <div class="mt-16 flex justify-center gap-3">
                <?php if($page > 1): ?>
                    <a href="?page=<?= $page-1 ?>" class="w-12 h-12 flex items-center justify-center rounded-full bg-white border border-slate-200 text-slate-600 hover:bg-slate-100 transition shadow-sm">←</a>
                <?php endif; ?>

                <?php for($i=1; $i<=$total_pages; $i++): ?>
                    <a href="?page=<?= $i ?>" class="w-12 h-12 flex items-center justify-center rounded-full font-bold transition shadow-sm <?= ($page == $i) ? 'bg-indigo-600 text-white shadow-indigo-500/30' : 'bg-white border border-slate-200 text-slate-600 hover:bg-slate-50' ?>">
                        <?= $i ?>
                    </a>
                <?php endfor; ?>

                <?php if($page < $total_pages): ?>
                    <a href="?page=<?= $page+1 ?>" class="w-12 h-12 flex items-center justify-center rounded-full bg-white border border-slate-200 text-slate-600 hover:bg-slate-100 transition shadow-sm">→</a>
                <?php endif; ?>
            </div>
            <?php endif; ?>

        <?php else: ?>
            <div class="text-center py-32">
                <div class="inline-flex items-center justify-center w-24 h-24 rounded-full bg-indigo-50 text-indigo-500 mb-6 animate-bounce">
                    <i data-lucide="bot" class="w-12 h-12"></i>
                </div>
                <h3 class="text-3xl font-bold text-slate-800 mb-2">AI Brain is Processing...</h3>
                <p class="text-slate-500 max-w-md mx-auto">
                    The automated writer is generating fresh content based on current trends. Check back in 5 minutes!
                </p>
            </div>
        <?php endif; ?>

    </div>
</div>

<script>
    lucide.createIcons();
</script>

<style>
    @keyframes fadeInUp {
        from { opacity: 0; transform: translateY(20px); }
        to { opacity: 1; transform: translateY(0); }
    }
    .animate-fade-in-up {
        animation: fadeInUp 0.8s ease-out forwards;
        opacity: 0;
    }
</style>

<?php include 'user/_footer.php'; ?>