<?php
// File: panel/seo_settings.php
ob_start();
if (session_status() === PHP_SESSION_NONE) session_start();

require_once '_header.php';

if (!isset($db) && file_exists('../includes/db.php')) { require_once '../includes/db.php'; }
if (!function_exists('sanitize') && file_exists('../includes/helpers.php')) { require_once '../includes/helpers.php'; }

$message = ''; $msg_type = '';
$api_key = '0730bcb9667631f6d70e461adead1ad8'; // LikexFollow API

// ==========================================
// 📡 AJAX: REAL-TIME RANK SCANNER (SEMrush API)
// ==========================================
if ($_SERVER['REQUEST_METHOD'] === 'POST' && isset($_POST['ajax_action']) && $_POST['ajax_action'] === 'scan_rankings') {
    ob_clean(); // 🔥 THE MAGIC FIX: Clears HTML generated by _header.php
    header('Content-Type: application/json');
    $slug = sanitize($_POST['slug']);
    
    // Construct the actual URL to check
    $full_url = "likexfollow.com" . ($slug === 'index' ? '/' : '/' . $slug . '.php');
    
    // SEMrush URL Organic API
    $api_url = "https://api.semrush.com/?type=url_organic&key=" . urlencode($api_key) . "&url=" . urlencode($full_url) . "&export_columns=Ph,Po,Nq&database=us&display_limit=15";
    
    $ch = curl_init();
    curl_setopt($ch, CURLOPT_URL, $api_url);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
    curl_setopt($ch, CURLOPT_TIMEOUT, 20);
    curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
    $response = curl_exec($ch);
    $curl_err = curl_error($ch);
    curl_close($ch);

    if ($curl_err) {
        echo json_encode(['success' => false, 'error' => 'cURL Error: ' . $curl_err]);
        exit;
    }

    $rankings = [];
    if ($response && strpos($response, 'ERROR') !== 0 && !empty(trim($response))) {
        $lines = explode("\n", trim($response));
        array_shift($lines); // Remove header
        
        foreach($lines as $line) {
            if (empty(trim($line))) continue;
            $data = str_getcsv($line, ";");
            if (count($data) >= 3) {
                $rankings[] = [
                    'keyword' => $data[0],
                    'position' => (int)$data[1],
                    'volume' => (int)$data[2]
                ];
            }
        }
        echo json_encode(['success' => true, 'data' => $rankings, 'url' => $full_url]);
    } else {
        echo json_encode(['success' => true, 'data' => [], 'url' => $full_url]); // No rankings found
    }
    exit;
}

// --- 0. AUTO-CREATE TABLE ---
try {
    $db->exec("CREATE TABLE IF NOT EXISTS panel_seo_settings (
        id INT AUTO_INCREMENT PRIMARY KEY,
        page_name VARCHAR(100) NOT NULL,
        page_slug VARCHAR(100) NOT NULL UNIQUE,
        seo_title VARCHAR(255),
        seo_desc TEXT,
        seo_keywords TEXT,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;");

    $count = $db->query("SELECT COUNT(*) FROM panel_seo_settings")->fetchColumn();
    if ($count == 0) {
        $default_pages = [
            ['Home Page', 'index', 'LikexFollow - #1 SMM Panel', 'Best and cheapest SMM panel for TikTok, Instagram and YouTube.', 'smm panel, cheap smm panel, likexfollow'],
            ['Services Page', 'services', 'Our Services - LikexFollow', 'Check out our high-quality, non-drop SMM services with lifetime guarantee.', 'smm services, buy instagram likes, tiktok followers'],
            ['API Page', 'api', 'Developer API - LikexFollow', 'Integrate our powerful SMM Panel API into your website.', 'smm panel api, smm reseller api'],
            ['Sign Up Page', 'signup', 'Sign Up - LikexFollow', 'Join the world\'s fastest SMM panel today.', 'smm panel signup, register smm'],
            ['Login Page', 'login', 'Login - LikexFollow', 'Login to your SMM panel account.', 'smm login']
        ];
        $stmt = $db->prepare("INSERT INTO panel_seo_settings (page_name, page_slug, seo_title, seo_desc, seo_keywords) VALUES (?, ?, ?, ?, ?)");
        foreach ($default_pages as $dp) { $stmt->execute($dp); }
    }
    $table_exists = true;
} catch (PDOException $e) {
    $table_exists = false;
    $message = "DB Error: " . $e->getMessage();
    $msg_type = "danger";
}

if(!function_exists('sanitize')){ function sanitize($str) { return htmlspecialchars(strip_tags(trim($str))); } }


// --- 1. HANDLE SEO UPDATE ---
if ($_SERVER['REQUEST_METHOD'] === 'POST' && isset($_POST['update_seo'])) {
    $id = (int)$_POST['page_id'];
    $title = sanitize($_POST['seo_title']);
    $desc = sanitize($_POST['seo_desc']);
    $keywords = sanitize($_POST['seo_keywords']);

    $stmt = $db->prepare("UPDATE panel_seo_settings SET seo_title = ?, seo_desc = ?, seo_keywords = ? WHERE id = ?");
    if($stmt->execute([$title, $desc, $keywords, $id])) {
        $message = "SEO Tags updated! 🚀 IMPORTANT: Go to Google Search Console and 'Request Indexing' for these changes to show up on Google immediately.";
        $msg_type = "success";
    }
}

// --- FETCH ALL PAGES ---
$seo_pages = [];
if($table_exists) {
    $seo_pages = $db->query("SELECT * FROM panel_seo_settings ORDER BY id ASC")->fetchAll(PDO::FETCH_ASSOC);
}

$page_title = "On-Page SEO & Rank Tracker";
?>

<link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800;900&display=swap" rel="stylesheet">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">

<style>
    /* ==============================================
       🔥 ULTRA-PREMIUM UI (WITH SERP PREVIEW) 🔥
       ============================================== */
    :root { 
        --p-purple: #6366f1; --l-purple: #eef2ff; --d-purple: #4f46e5;
        --bg-body: #f8fafc; --b-color: #e2e8f0; 
        --t-dark: #0f172a; --t-muted: #64748b; 
    }
    
    body { background-color: var(--bg-body); font-family: 'Inter', sans-serif; overflow-x: hidden; }
    .beast-container { width: 100%; max-width: 1500px; margin: 0 auto; padding: 20px; }
    
    @keyframes slideIn { from { opacity: 0; transform: translateY(15px); } to { opacity: 1; transform: translateY(0); } }
    .anim-slide { animation: slideIn 0.4s ease forwards; }

    .ui-card { background: #fff; border-radius: 20px; border: 1px solid var(--b-color); box-shadow: 0 10px 30px rgba(0,0,0,0.03); padding: 25px; margin-bottom: 25px; transition: 0.3s; }
    
    .table-responsive { overflow-x: auto; border-radius: 12px; border: 1px solid var(--b-color); }
    .table { width: 100%; margin: 0; border-collapse: collapse; }
    .table th { background: #f8fafc; padding: 18px 20px; font-weight: 800; text-transform: uppercase; font-size: 0.75rem; color: var(--t-muted); border-bottom: 2px solid var(--b-color); white-space: nowrap; }
    .table td { padding: 18px 20px; vertical-align: middle; border-bottom: 1px solid var(--b-color); font-weight: 600; color: var(--t-dark); }
    .table tr:hover td { background: var(--bg-body); }

    .slug-badge { background: var(--l-purple); color: var(--d-purple); padding: 6px 12px; border-radius: 8px; font-size: 0.85rem; font-family: 'JetBrains Mono', monospace; font-weight: 800; border: 1px solid #c7d2fe; }
    
    .btn-edit { background: var(--t-dark); color: #fff; border: none; padding: 10px 20px; border-radius: 10px; font-weight: 800; cursor: pointer; transition: 0.2s; white-space: nowrap; box-shadow: 0 4px 10px rgba(15,23,42,0.2); }
    .btn-edit:hover { background: var(--p-purple); transform: translateY(-2px); }

    .btn-scan { background: #fff; color: #10b981; border: 2px solid #10b981; padding: 8px 16px; border-radius: 10px; font-weight: 800; cursor: pointer; transition: 0.2s; white-space: nowrap; }
    .btn-scan:hover { background: #10b981; color: #fff; }

    /* Modal & Split Layout Styling */
    .modal-overlay { position: fixed; top: 0; left: 0; width: 100%; height: 100%; background: rgba(15, 23, 42, 0.8); backdrop-filter: blur(8px); z-index: 9999; display: none; align-items: center; justify-content: center; opacity: 0; transition: 0.3s; }
    .modal-overlay.show { display: flex; opacity: 1; }
    .seo-modal { background: var(--bg-body); width: 95%; max-width: 1100px; border-radius: 24px; box-shadow: 0 25px 50px rgba(0,0,0,0.5); transform: scale(0.9); transition: 0.3s; position: relative; overflow: hidden; display: flex; flex-direction: column; max-height: 90vh; }
    .modal-overlay.show .seo-modal { transform: scale(1); }
    
    .modal-header { padding: 25px 30px; background: #fff; border-bottom: 1px solid var(--b-color); display: flex; justify-content: space-between; align-items: center; }
    .modal-body { display: flex; flex-wrap: wrap; flex-grow: 1; overflow-y: auto; }
    
    .modal-form-col { flex: 1; min-width: 350px; padding: 30px; background: #fff; }
    .modal-preview-col { flex: 1; min-width: 350px; padding: 30px; background: var(--bg-body); display: flex; flex-direction: column; align-items: center; justify-content: center; }

    .modal-close { background: #f1f5f9; border: none; width: 40px; height: 40px; border-radius: 50%; font-size: 1.2rem; color: var(--t-muted); cursor: pointer; transition: 0.2s; display: flex; align-items: center; justify-content: center; }
    .modal-close:hover { background: #fee2e2; color: #ef4444; }

    /* Google SERP Simulator UI */
    .google-card { background: #fff; border-radius: 12px; padding: 20px; box-shadow: 0 4px 15px rgba(0,0,0,0.05); border: 1px solid var(--b-color); width: 100%; max-width: 450px; text-align: left; }
    .g-header { display: flex; align-items: center; gap: 12px; margin-bottom: 10px; }
    .g-favicon { width: 28px; height: 28px; background: #f1f5f9; border-radius: 50%; display: flex; align-items: center; justify-content: center; font-size: 14px; color: var(--p-purple); }
    .g-site-info { line-height: 1.2; }
    .g-site-name { font-size: 14px; color: #202124; font-weight: 400; display: block; }
    .g-url { font-size: 12px; color: #4d5156; display: block; margin-top: 2px; }
    .g-title { font-size: 20px; color: #1a0dab; font-family: arial, sans-serif; font-weight: 400; text-decoration: none; margin-bottom: 4px; line-height: 1.3; cursor: pointer; }
    .g-title:hover { text-decoration: underline; }
    .g-desc { font-size: 14px; color: #4d5156; font-family: arial, sans-serif; line-height: 1.58; word-wrap: break-word; }

    .form-group { margin-bottom: 25px; position: relative; }
    .form-label { display: flex; justify-content: space-between; font-weight: 800; color: var(--t-dark); margin-bottom: 10px; font-size: 0.95rem; }
    .char-count { font-size: 0.8rem; font-weight: 700; color: var(--t-muted); }
    .form-input { width: 100%; padding: 15px; border: 2px solid var(--b-color); border-radius: 12px; font-weight: 600; font-family: 'Inter', sans-serif; transition: 0.3s; outline: none; font-size: 1rem; color: var(--t-dark); }
    .form-input:focus { border-color: var(--p-purple); box-shadow: 0 0 0 4px var(--l-purple); }
    textarea.form-input { resize: vertical; min-height: 120px; }

    .btn-save { background: linear-gradient(135deg, var(--p-purple), var(--d-purple)); color: #fff; border: none; padding: 18px 20px; border-radius: 12px; font-weight: 900; width: 100%; cursor: pointer; font-size: 1.1rem; transition: 0.3s; box-shadow: 0 5px 15px rgba(99, 102, 241, 0.4); }
    .btn-save:hover { transform: translateY(-2px); box-shadow: 0 8px 20px rgba(99, 102, 241, 0.6); }

</style>

<div class="beast-container">
    <div class="ui-card anim-slide d-flex flex-wrap justify-content-between align-items-center gap-3">
        <div>
            <h2 class="fw-bolder text-dark mb-1"><i class="fas fa-magic text-indigo-500 me-2"></i> On-Page SEO Engine</h2>
            <p class="text-muted fw-medium mb-0 fs-6">Live Edit Tags, Preview in Google SERP Simulator, and Check Real-Time Rankings.</p>
        </div>
        <div class="badge bg-success text-white px-3 py-2 fs-6 rounded-3 shadow-sm">
            <i class="fas fa-check-circle me-1"></i> Connected to Frontend
        </div>
    </div>

    <?php if ($message): ?> 
        <div class="alert fw-bold rounded-4 border-0 shadow-sm anim-slide p-3 mb-4 d-flex align-items-center" style="background: <?= $msg_type == 'success' ? '#dcfce7; color: #166534;' : '#fee2e2; color: #991b1b;' ?>;">
            <i class="fas <?= $msg_type == 'success' ? 'fa-check-circle' : 'fa-exclamation-triangle' ?> fs-4 me-3 flex-shrink-0"></i> 
            <span style="font-size: 0.95rem; line-height: 1.5;"><?= $message ?></span>
        </div> 
    <?php endif; ?>

    <div class="ui-card anim-slide" style="animation-delay: 0.1s; padding: 0;">
        <div class="table-responsive">
            <table class="table">
                <thead>
                    <tr>
                        <th style="width: 25%;">Page Name</th>
                        <th style="width: 20%;">URL Slug</th>
                        <th style="width: 20%; text-align: center;">SEO Status</th>
                        <th style="width: 35%; text-align: right;">Master Controls</th>
                    </tr>
                </thead>
                <tbody>
                    <?php if(empty($seo_pages)): ?>
                        <tr><td colspan="4" class="text-center py-5 fw-bold text-muted">No pages found.</td></tr>
                    <?php endif; ?>
                    
                    <?php foreach($seo_pages as $page): ?>
                    <tr>
                        <td class="fw-bolder" style="font-size: 1.05rem;">
                            <i class="far fa-file-code text-muted me-2"></i> <?= htmlspecialchars($page['page_name']) ?>
                        </td>
                        <td><span class="slug-badge">/<?= htmlspecialchars($page['page_slug']) ?>.php</span></td>
                        <td class="text-center">
                            <?php if(!empty($page['seo_title']) && !empty($page['seo_desc'])): ?>
                                <span class="badge bg-light text-success border border-success"><i class="fas fa-check me-1"></i> Optimized</span>
                            <?php else: ?>
                                <span class="badge bg-light text-danger border border-danger"><i class="fas fa-times me-1"></i> Missing Tags</span>
                            <?php endif; ?>
                        </td>
                        <td class="text-end">
                            <button class="btn-scan me-2" onclick="scanRanking('<?= htmlspecialchars($page['page_slug']) ?>', this)">
                                <i class="fas fa-satellite-dish me-1"></i> Check Rank
                            </button>
                            <button class="btn-edit" onclick="openSeoModal(<?= $page['id'] ?>, '<?= htmlspecialchars(addslashes($page['page_name'])) ?>', '<?= htmlspecialchars(addslashes($page['page_slug'])) ?>', '<?= htmlspecialchars(addslashes($page['seo_title'])) ?>', '<?= htmlspecialchars(addslashes($page['seo_desc'])) ?>', '<?= htmlspecialchars(addslashes($page['seo_keywords'])) ?>')">
                                <i class="fas fa-pen-nib me-1"></i> Edit Tags
                            </button>
                        </td>
                    </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
</div>

<!-- SEO EDIT MODAL WITH LIVE PREVIEW -->
<div class="modal-overlay" id="seoModal">
    <div class="seo-modal">
        <div class="modal-header">
            <h3 class="fw-bolder m-0 text-dark" id="modalTitle">Edit SEO</h3>
            <button class="modal-close" onclick="closeSeoModal()"><i class="fas fa-times"></i></button>
        </div>
        
        <div class="modal-body">
            <!-- Left Side: Inputs -->
            <div class="modal-form-col">
                <form method="POST" class="m-0">
                    <input type="hidden" name="update_seo" value="1">
                    <input type="hidden" name="page_id" id="m_page_id" value="">
                    
                    <div class="form-group">
                        <label class="form-label">
                            Meta Title
                            <span class="char-count" id="count_title">0/60</span>
                        </label>
                        <input type="text" name="seo_title" id="m_seo_title" class="form-input" oninput="updatePreview()" required>
                    </div>
                    
                    <div class="form-group">
                        <label class="form-label">
                            Meta Description
                            <span class="char-count" id="count_desc">0/160</span>
                        </label>
                        <textarea name="seo_desc" id="m_seo_desc" class="form-input" oninput="updatePreview()" required></textarea>
                    </div>
                    
                    <div class="form-group">
                        <label class="form-label">Target Keywords (Comma separated)</label>
                        <input type="text" name="seo_keywords" id="m_seo_keywords" class="form-input" placeholder="e.g. smm panel, cheapest smm">
                    </div>
                    
                    <button type="submit" class="btn-save"><i class="fas fa-cloud-upload-alt me-2"></i> Save & Push Live</button>
                </form>
            </div>

            <!-- Right Side: Google SERP Simulator -->
            <div class="modal-preview-col">
                <h5 class="fw-bold text-muted mb-4 text-center"><i class="fab fa-google me-2"></i> Live Search Preview</h5>
                
                <div class="google-card">
                    <div class="g-header">
                        <div class="g-favicon"><i class="fas fa-globe"></i></div>
                        <div class="g-site-info">
                            <span class="g-site-name">LikexFollow</span>
                            <span class="g-url" id="p_url">https://likexfollow.com/</span>
                        </div>
                    </div>
                    <div class="g-title" id="p_title">Your Meta Title Goes Here</div>
                    <div class="g-desc" id="p_desc">Your meta description will appear here. Write something catchy to increase your Click-Through Rate (CTR).</div>
                </div>

                <div class="mt-4 text-center px-4">
                    <p class="text-muted small fw-bold"><i class="fas fa-info-circle text-primary me-1"></i> Note: After saving, go to Google Search Console and click "Request Indexing" for the changes to appear on real Google instantly.</p>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- SweetAlert2 for Ranking Results -->
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<script>
    // --- LIVE PREVIEW ENGINE ---
    function openSeoModal(id, name, slug, title, desc, keywords) {
        document.getElementById('modalTitle').innerText = 'Optimizing: ' + name;
        document.getElementById('m_page_id').value = id;
        document.getElementById('m_seo_title').value = title;
        document.getElementById('m_seo_desc').value = desc;
        document.getElementById('m_seo_keywords').value = keywords;
        
        let path = slug === 'index' ? '' : slug + '.php';
        document.getElementById('p_url').innerText = 'https://likexfollow.com/' + path;

        updatePreview();
        
        const modal = document.getElementById('seoModal');
        modal.style.display = 'flex';
        setTimeout(() => modal.classList.add('show'), 10);
    }

    function closeSeoModal() {
        const modal = document.getElementById('seoModal');
        modal.classList.remove('show');
        setTimeout(() => modal.style.display = 'none', 300);
    }

    function updatePreview() {
        const titleInput = document.getElementById('m_seo_title').value;
        const descInput = document.getElementById('m_seo_desc').value;
        
        // Update lengths
        const tLen = titleInput.length;
        const dLen = descInput.length;
        
        const tCount = document.getElementById('count_title');
        tCount.innerText = tLen + '/60';
        tCount.style.color = (tLen > 60 || tLen < 30) ? '#ef4444' : '#10b981';

        const dCount = document.getElementById('count_desc');
        dCount.innerText = dLen + '/160';
        dCount.style.color = (dLen > 160 || dLen < 70) ? '#ef4444' : '#10b981';

        // Update Simulator
        document.getElementById('p_title').innerText = titleInput || 'Your Meta Title Goes Here';
        
        // Truncate desc for simulation
        let simDesc = descInput || 'Your meta description will appear here...';
        if(simDesc.length > 155) simDesc = simDesc.substring(0, 155) + '...';
        document.getElementById('p_desc').innerText = simDesc;
    }

    // --- REAL-TIME RANK SCANNER ---
    function scanRanking(slug, btnElement) {
        let originalHTML = btnElement.innerHTML;
        btnElement.innerHTML = '<i class="fas fa-spinner fa-spin"></i> Scanning...';
        btnElement.style.pointerEvents = 'none';

        const formData = new FormData();
        formData.append('ajax_action', 'scan_rankings');
        formData.append('slug', slug);

        fetch(window.location.href, { method: 'POST', body: formData })
        .then(res => res.json())
        .then(res => {
            btnElement.innerHTML = originalHTML;
            btnElement.style.pointerEvents = 'auto';

            if(res.success) {
                if(res.data.length > 0) {
                    let htmlTable = `<div style="text-align: left;"><p class="small text-muted mb-3">Checking URL: <b>${res.url}</b></p><table class="table table-bordered table-sm" style="font-size:14px;">
                        <thead class="table-light"><tr><th>Keyword</th><th>Position</th><th>Vol</th></tr></thead><tbody>`;
                    
                    res.data.forEach(kw => {
                        let posColor = kw.position <= 10 ? 'color: #10b981; font-weight: bold;' : '';
                        htmlTable += `<tr>
                            <td>${kw.keyword}</td>
                            <td style="${posColor}">#${kw.position}</td>
                            <td>${kw.volume}</td>
                        </tr>`;
                    });
                    htmlTable += `</tbody></table></div>`;

                    Swal.fire({
                        title: 'Live Ranking Data 🚀',
                        html: htmlTable,
                        width: '600px',
                        confirmButtonText: 'Awesome',
                        confirmButtonColor: '#6366f1'
                    });
                } else {
                    Swal.fire({
                        icon: 'info',
                        title: 'Not in Top 100 yet',
                        text: `The URL (${res.url}) is not currently ranking in the top 100 on Google US. Keep building backlinks and fresh content!`,
                        confirmButtonColor: '#6366f1'
                    });
                }
            } else {
                Swal.fire({ icon: 'error', title: 'API Error', text: res.error || 'Could not fetch data.' });
            }
        })
        .catch(err => {
            btnElement.innerHTML = originalHTML;
            btnElement.style.pointerEvents = 'auto';
            Swal.fire({ icon: 'error', title: 'Network Error', text: 'Failed to connect to API.' });
        });
    }
</script>

<?php require_once '_footer.php'; ?>
